= Instructions

== Generate the slideshow and hands-on-labs

You need https://github.com/asciidoctor/asciidoctor[Asciidoctor] and
https://github.com/asciidoctor/asciidoctor-reveal.js[reveal.js Backend for Asciidoctor]
to generate the slideshow and hands-on-lab from the asciidoc files.

See https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/README.adoc[reveal.js Backend for Asciidoctor]
for more infos how to generate the slides from the Asciidoctor templates.

=== Prerequisites

. Install http://bundler.io/[bundler] (if not already installed)  using your system's package manager or with:

  $ gem install bundler

. If you're using RVM, make sure you switch away from any gemset:

  $ rvm use default
+
or
+
  $ rvm use system


=== Install Asciidoctor & reveal.js

. Install the gems into the project

  $ rm -f Gemfile.lock
  $ bundle config --local github.https true
  $ bundle --path=.bundle/gems --binstubs=.bundle/.bin

. Optional: Copy or clone reveal.js presentation framework.
  Allows you to modify themes or view slides offline.

  $ git clone --depth 1 git@github.com:ksobkowiak-talks/reveal.js.git

=== Generate slides

  $ bundle exec asciidoctor-revealjs slides.adoc

=== Display the presentation

It's recommended to use http server to server the generated content. You can use
`http-server` or `jekyll`.

==== `http-server`

To use `http-server` you need to insall https://nodejs.org/en/download[Node.js]
and next the `http-server`

  $ npm install http-server -g

Next you can server the content using command

  $ http-server

The content is available under http://127.0.0.1:8080/slides.html

==== `jekyll`

To use `jekyll` you have to install the gem first

  $ gem install jekyll

Next you can server the content using command

  $ jekyll serve

The content is available under http://127.0.0.1:4000/slides.html

=== Generate PDF

==== Install DeckTape

  $ git clone https://github.com/astefanutti/decktape.git .decktape
  $ mkdir .decktape/bin
  $ curl -L https://github.com/astefanutti/decktape/releases/download/v1.0.0/phantomjs-linux-x86-64 -o .decktape/bin/phantomjs
  $ chmod +x .decktape/bin/phantomjs

==== Generate the PDF file

   $ .decktape/bin/phantomjs .decktape/decktape.js slides.html slides.pdf


== Modify the reveal.js theme

=== Prerequisites

. Install [Node.js](http://nodejs.org/) (4.0.0 or later)

. Navigate to the reveal.js folder

  $ cd reveal.js

. Install dependencies

   $ npm install

=== Build the theme

. Build the theme using

  $ grunt css-themes
